apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: counter-backend
  labels:
    app: counter-backend
    app.kubernetes.io/part-of: counter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter-backend
  minReplicas: 2
  maxReplicas: 6
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50